# Generated by Django 3.1.2 on 2020-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201029_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='press',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
