# Generated by Django 3.1.2 on 2020-10-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='bz_user',
        ),
    ]
